// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Teste_Dev_FullStack.Infraestructure.Data;

#nullable disable

namespace Teste_Dev_FullStack.Migrations
{
    [DbContext(typeof(MyContextDB))]
    [Migration("20260205164449_InitialMigrations")]
    partial class InitialMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Teste_Dev_FullStack.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PurposeCategory")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CategoriesSet");
                });

            modelBuilder.Entity("Teste_Dev_FullStack.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("PersonsSet");
                });

            modelBuilder.Entity("Teste_Dev_FullStack.Domain.Entities.Transection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<int>("TransectionType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("TransectionsSet");
                });

            modelBuilder.Entity("Teste_Dev_FullStack.Domain.Entities.Transection", b =>
                {
                    b.HasOne("Teste_Dev_FullStack.Domain.Entities.Person", null)
                        .WithOne("Transection")
                        .HasForeignKey("Teste_Dev_FullStack.Domain.Entities.Transection", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Teste_Dev_FullStack.Domain.Entities.Person", b =>
                {
                    b.Navigation("Transection")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
